const fs=require('fs'),assert=require('assert'),vm=require('vm');
const read=p=>fs.readFileSync(__dirname+'/'+p,'utf8'),json=p=>JSON.parse(read(p));
const html=read('index.html'),before=read('../ecoworld-visitor-v5-1/index.html'),script=s=>s.match(/<script>\s*([\s\S]*?)<\/script>/)[1];new vm.Script(script(html));
for(const k of ['MAPBOX_PUBLIC_TOKEN','EMBEDDED_GEOJSON','FACILITY_PHOTOS']){const r=new RegExp('const '+k+' ?= ?(.*);');assert.equal(html.match(r)[1],before.match(r)[1]);}
for(const [a,b] of [['const R=','// ---- UI / Mapbox ----'],['function showPoint','function fitFacilities']])assert.equal(script(html).slice(script(html).indexOf(a),script(html).indexOf(b)),script(before).slice(script(before).indexOf(a),script(before).indexOf(b)));
const structures=json('ecotown-structures.geojson').features,network=json('review-network.geojson').features,nodes=network.filter(f=>f.geometry.type==='Point'),links=network.filter(f=>f.geometry.type==='LineString'),cfg=json('model-config.json');
const geo=JSON.parse(html.match(/const EMBEDDED_GEOJSON = (.*);/)[1]),buildings=geo.features.filter(f=>cfg.buildings.some(b=>b.id===f.properties.id));
assert.equal(new Set([...structures,...network].map(f=>f.id)).size,structures.length+network.length);
function inside(p,r){let v=false;for(let i=0,j=r.length-1;i<r.length;j=i++){let a=r[i],b=r[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])v=!v;}return v;}
function crosses(a,b,c,d){const orient=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);return orient(a,b,c)*orient(a,b,d)<-1e-24&&orient(c,d,a)*orient(c,d,b)<-1e-24;}
for(const f of structures){const p=f.properties;assert(p.base_m>=0&&p.top_m>p.base_m);assert.equal(p.base_m,p.relative_base_m+4);assert.equal(p.top_m,p.relative_top_m+4);assert.equal(p.routing_enabled,false);assert.equal(p.survey_verified,false);for(const r of f.geometry.coordinates){assert.deepEqual(r[0],r.at(-1));assert(r.every(p=>p.length===2&&p.every(Number.isFinite)));for(let i=0;i<r.length-1;i++)for(let j=i+2;j<r.length-1;j++)if(!(i===0&&j===r.length-2))assert(!crosses(r[i],r[i+1],r[j],r[j+1]),f.id+' self intersection');}}
const cutout=structures.find(f=>f.id==='central-sunken-terrain');assert.equal(cutout.geometry.coordinates.length,2);assert(cutout.geometry.coordinates[1].every(p=>inside(p,cutout.geometry.coordinates[0])));
for(const b of cfg.buildings){const f=structures.find(f=>f.id===b.id+'-g1').properties;assert.equal(f.base_m,4);assert.equal(f.top_m,8);const floors=structures.filter(f=>f.properties.building_id===b.id&&f.properties.part==='eco upper floor');assert.equal(floors.length,b.above_ground_floors-1);assert.equal(Math.max(...floors.map(f=>f.properties.top_m)),4+4*b.above_ground_floors);}
const byId=new Map(nodes.map(n=>[n.id,n])),adj=new Map(nodes.map(n=>[n.id,[]]));
for(const l of links){const p=l.properties,a=byId.get(p.from_node),b=byId.get(p.to_node);assert(a&&b);assert.deepEqual(l.geometry.coordinates,[a.geometry.coordinates,b.geometry.coordinates]);assert.equal(p.relative_start_m,a.properties.relative_height_m);assert.equal(p.relative_end_m,b.properties.relative_height_m);assert.equal(p.routing_enabled,false);adj.get(a.id).push(b.id);adj.get(b.id).push(a.id);if(a.properties.level!==b.properties.level)assert(p.vertical_transition);for(const building of buildings){const r=building.geometry.coordinates[0],[a,b]=l.geometry.coordinates;assert(!inside(a,r)&&!inside(b,r),l.id+' endpoint inside '+building.properties.id);for(let i=0;i<r.length-1;i++)assert(!crosses(a,b,r[i],r[i+1]),l.id+' crosses '+building.properties.id);}}
const seen=new Set(),queue=['entry-b1'];while(queue.length){const id=queue.pop();if(seen.has(id))continue;seen.add(id);queue.push(...adj.get(id));}assert.equal(seen.size,nodes.length);
const floor=structures.find(f=>f.id==='lower-courtyard-floor').geometry.coordinates[0];for(const b of buildings){const r=b.geometry.coordinates[0];assert(!floor.some(p=>inside(p,r)),'lower floor vertex overlaps building');for(let i=0;i<floor.length-1;i++)for(let j=0;j<r.length-1;j++)assert(!crosses(floor[i],floor[i+1],r[j],r[j+1]),'lower floor crosses building');}
const result={passed:true,structural_features:structures.length,nodes:nodes.length,links:links.length,connected_components:1,checks:['original token, data, photos and GPS preserved','nonnegative renderer elevations and signed relative datum','G1 and upper floor separation','closed rings, no self intersections and sunken hole containment','shared link endpoints and explicit vertical transitions','reference lines do not cross original building interiors','lower courtyard does not cross building interiors'],not_verified:['real-world horizontal/vertical accuracy','actual stairs and accessibility','Mapbox runtime and on-site appearance']};fs.writeFileSync(__dirname+'/validation.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
