// Geometry QA drawing, not a Mapbox capture or surveyed map.
const fs=require('fs'),sharp=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const cfg=JSON.parse(fs.readFileSync(__dirname+'/model-config.json','utf8')),data=JSON.parse(fs.readFileSync(__dirname+'/ecotown-structures.geojson','utf8')).features,lines=JSON.parse(fs.readFileSync(__dirname+'/ecotown-walkways.geojson','utf8')).features;
const project=p=>[140+(p[0]-128.0589)*89400*5,140+(36.6553-p[1])*111195*5];
const path=f=>f.geometry.coordinates.map(r=>'M'+r.map(p=>project(p).join(',')).join('L')+'Z').join(' ');
let body='';
for(const f of [...data].sort((a,b)=>a.properties.top_m-b.properties.top_m)){const p=f.properties;if(p.part.includes('mullion'))continue;body+=`<path d="${path(f)}" fill="${p.annotation_color}" stroke="#4d625c" stroke-width=".7" fill-rule="evenodd"/>`;}
for(const l of lines){body+=`<path d="M${l.geometry.coordinates.map(p=>project(p).join(',')).join('L')}" fill="none" stroke="white" stroke-width="6"/><path d="M${l.geometry.coordinates.map(p=>project(p).join(',')).join('L')}" fill="none" stroke="#294ccd" stroke-width="3" ${l.properties.vertical_transition?'stroke-dasharray="4 3"':''}/>`;}
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="1110"><rect width="1280" height="1110" fill="#f4f4e9"/><text x="40" y="48" font-family="Arial" font-size="27" fill="#254e49">Eco Town v5.2 - floor separation / route review</text><text x="40" y="80" font-family="Arial" font-size="16" fill="#64776a">Plan projection from generated geometry. NOT a Mapbox screenshot or an orthophoto trace.</text>${body}<rect x="900" y="120" width="350" height="268" fill="white" rx="12"/><text x="920" y="157" font-family="Arial" font-size="21" fill="#254e49">Rendering datum</text><text x="920" y="195" font-family="Arial" font-size="18">B1: -4 m relative / render 0 m</text><text x="920" y="226" font-family="Arial" font-size="18">G1 floor: 0 m / render 4 m</text><text x="920" y="257" font-family="Arial" font-size="18">G2 floor: +4 m / render 8 m</text><text x="920" y="288" font-family="Arial" font-size="18">G3 floor: +8 m / render 12 m</text><text x="920" y="330" font-family="Arial" font-size="16">Blue = review walking links</text><text x="920" y="357" font-family="Arial" font-size="16">Dashed = inferred level transition</text><text x="40" y="1065" font-family="Arial" font-size="17" fill="#52685d">26 shared nodes / 25 links - connectivity checked; physical access and levels remain unverified.</text></svg>`;
sharp(Buffer.from(svg)).png().toFile(__dirname+'/geometry-plan.png').then(()=>console.log('Saved geometry-plan.png'));
