// Offline geometry illustration only. This is not a Mapbox screenshot.
const fs=require('fs'),sharp=require('C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const after=JSON.parse(fs.readFileSync(__dirname+'/visual-models.geojson','utf8')).features;
const before=JSON.parse(fs.readFileSync(__dirname+'/../ecoworld-visitor-v5/visual-models.geojson','utf8')).features;
const origin=[128.05965,36.6546],angle=-25*Math.PI/180,pitch=60*Math.PI/180;
const xyz=(p,z)=>{const x=(p[0]-origin[0])*89400,y=(p[1]-origin[1])*111195;const u=x*Math.cos(angle)-y*Math.sin(angle),v=x*Math.sin(angle)+y*Math.cos(angle);return [u,-v*Math.cos(pitch)-z*Math.sin(pitch),v*Math.sin(pitch)-z*Math.cos(pitch)];};
const choose=f=>f.properties.part.startsWith('eco ')||f.properties.part.startsWith('solar');
function faces(features){const list=[];for(const f of features.filter(choose)){const r=f.geometry.coordinates[0],b=f.properties.base,h=f.properties.height;list.push({pts:r.slice(0,-1).map(p=>xyz(p,h)),color:f.properties.color,shade:1});for(let i=0;i<r.length-1;i++)list.push({pts:[xyz(r[i],b),xyz(r[i+1],b),xyz(r[i+1],h),xyz(r[i],h)],color:f.properties.color,shade:.76+(.08*(i%3))});}return list.sort((a,b)=>b.pts.reduce((s,p)=>s+p[2],0)/b.pts.length-a.pts.reduce((s,p)=>s+p[2],0)/a.pts.length);}
const all=[...faces(before),...faces(after)].flatMap(f=>f.pts),minX=Math.min(...all.map(p=>p[0])),maxX=Math.max(...all.map(p=>p[0])),minY=Math.min(...all.map(p=>p[1])),maxY=Math.max(...all.map(p=>p[1])),scale=Math.min(620/(maxX-minX),470/(maxY-minY));
function panel(faces,left){return faces.map(f=>{let color=f.color.match(/\w\w/g).map(v=>Math.round(parseInt(v,16)*f.shade));return `<polygon points="${f.pts.map(p=>[(p[0]-minX)*scale+left,(p[1]-minY)*scale+185].join(',')).join(' ')}" fill="rgb(${color.join(',')})" stroke="#526356" stroke-opacity=".2" stroke-width=".45"/>`;}).join('');}
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="810"><rect width="1440" height="810" fill="#f4f6ed"/><text x="45" y="48" font-family="Arial" font-size="28" fill="#234d49">Eco Town - extrusion height comparison</text><text x="45" y="78" font-family="Arial" font-size="17" fill="#5c726b">Offline geometry projection / visual estimates / same scale / not a Mapbox screenshot</text><rect x="25" y="105" width="685" height="610" rx="18" fill="#e6ecd5"/><rect x="730" y="105" width="685" height="610" rx="18" fill="#e6ecd5"/><text x="50" y="147" font-family="Arial" font-size="23" fill="#325954">v5 - all walls: 8 m</text><text x="755" y="147" font-family="Arial" font-size="23" fill="#325954">v5.1 - main: 12 m / others: 8 m</text>${panel(faces(before),55)}${panel(faces(after),760)}<text x="755" y="750" font-family="Arial" font-size="18" fill="#325954">Ground bases: 0 / 0.6 / 1.2 m; terrace levels: 0.15 / 0.75 / 1.2 m</text><text x="45" y="786" font-family="Arial" font-size="15" fill="#6d7a6f">Building and route coordinates preserved. Vertical dimensions are adjustable illustration values.</text></svg>`;
sharp(Buffer.from(svg)).png().toFile(__dirname+'/height-comparison.png').then(()=>console.log('Geometry comparison generated.'));
